#       ________                                     ____  ___
#       \_____  \ ___  ______.__. ____   ____   ____ \   \/  /
#        /   |   \\  \/  <   |  |/ ___\_/ __ \ /    \ \     /
#       /    |    \>    < \___  / /_/  >  ___/|   |  \/     \
#       \_______  /__/\_ \/ ____\___  / \___  >___|  /___/\  \
#               \/      \/\/   /_____/      \/     \/      \_/
#
#                   -Created and coded by ShadowOxygen
#                   -Code cleaned and revised by MohanadHosny#9152
#                   -Settings file for OxygenX

OxygenX:

  # Check if current version of OxygenX is latest
  check_for_updates: true
  auto_update: true

  # How much times to check a account. Set it to as much as you can to avoid errors.
  # Needs to be 1 or higher
  retries: 8

  # Higher for better accuracy but slower (counted in milliseconds, example: 6000ms = 6 seconds)
  timeout: 6000

  # Threads for account checking (set to very small amount if you don't use proxy)
  threads: 100
  
  # Remove all combo duplicates
  combo_duplicates: true
  
  # Remove all proxy duplicates
  proxy_duplicates: true
  
  # Check hits if its a mail access
  mail_access: true
  
  # Save ranked accounts in NFA.txt or SFA.txt (Turn it off for ranked accounts NOT to save in NFA.txt or SFA.txt)
  save_ranked_type: true
  
  # Print bad accounts
  print_bad: true
  
  # Save bad accounts
  save_bad: true

  # Broken, please don't disable
  use_https: true

  # Normal users should keep this false unless problems start happening
  debugging: false
  
  # Cape check
  capes:
    liquidbounce: true
    optifine: true
    labymod:  false # Currently broken
    mojang:  true

  # Rank check
  rank:
    mineplex: true
    hypixel:  true
    hivemc: true
    veltpvp: true
    skyblock: true

  # Level check
  level:
    # Save "high level" accounts in different file than other
    hypixel: true
    mineplex: true
    
    # Minimum level to mark accounts as "high level"
    hypixel_level: 21
    mineplex_level: 21

  proxy:
    # If proxies should be used (it is HIGHLY recommended to use VPN and set "sleep_proxyless" if you don't want to get your ip blacklisted by Mojang)
    proxy: true
    # Proxy types: https | socks4 | socks5
    proxy_type: 'socks4'
    # EXPERMENTAL! Locks the proxy so other threads can't use it
    lock_proxy: true
    # EXPERMENTAL! Auto remove proxies (you can limit the proxies removed with proxy_remove_limit)
    remove_bad_proxy: true
    # EXPERMENTAL! If remove bad proxies are on, once the proxy list hits the limit it will stop removing bad proxies
    proxy_remove_limit: 5000
    # If proxies be used for checking SFA accounts
    proxy_for_sfa: true
    # Sleep between checks if proxy mode is false (put 0 for no sleep) counted in secouds
    sleep_proxyless: 5
    
    api:
      # If proxy api link to be used.
      use: false
      # If proxy_use_api is true, put api link in the parentheses
      api_link: "https://api.proxyscrape.com/?request=getproxies&proxytype=socks4&timeout=4000"
      # If proxy_use_api is true, put a number for seconds to refresh the link (every number under 30 is for no refreshing time, recommend refresh time: 300 seconds aka 5 minutes)
      refresh_time: 300
